version: '3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true  # Enable Security
      - xpack.security.http.ssl.enabled=true  # Enable HTTPS
      - xpack.security.http.ssl.keystore.path=/usr/share/elasticsearch/config/certs/es01.p12
      - xpack.security.http.ssl.truststore.path=/usr/share/elasticsearch/config/certs/elastic-stack-ca.p12
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.keystore.path=/usr/share/elasticsearch/config/certs/es01.p12
      - xpack.security.transport.ssl.truststore.path=/usr/share/elasticsearch/config/certs/elastic-stack-ca.p12
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./config/certs:/usr/share/elasticsearch/config/certs  # Mount the certificates directory
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - elastic_network
    ports:
      - 9301:9200  # Map port to 9301 for HTTPS

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.keystore.path=/usr/share/elasticsearch/config/certs/es02.p12
      - xpack.security.http.ssl.truststore.path=/usr/share/elasticsearch/config/certs/elastic-stack-ca.p12
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.keystore.path=/usr/share/elasticsearch/config/certs/es02.p12
      - xpack.security.transport.ssl.truststore.path=/usr/share/elasticsearch/config/certs/elastic-stack-ca.p12
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./config/certs:/usr/share/elasticsearch/config/certs  # Mount the certificates directory
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - elastic_network
    ports:
      - 9302:9200  # Map port to 9302 for HTTPS

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.keystore.path=/usr/share/elasticsearch/config/certs/es03.p12
      - xpack.security.http.ssl.truststore.path=/usr/share/elasticsearch/config/certs/elastic-stack-ca.p12
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.keystore.path=/usr/share/elasticsearch/config/certs/es03.p12
      - xpack.security.transport.ssl.truststore.path=/usr/share/elasticsearch/config/certs/elastic-stack-ca.p12
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./config/certs:/usr/share/elasticsearch/config/certs  # Mount the certificates directory
      - esdata3:/usr/share/elasticsearch/data
    networks:
      - elastic_network
    ports:
      - 9303:9200  # Map port to 9303 for HTTPS

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local

networks:
  elastic_network:
    driver: bridge
