version: '3'
services:
  elasticsearch:
    image: harbor.int.taqniat.ae/elastic/elasticsearch:8.16.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic_network
    volumes:
      - esdata:/usr/share/elasticsearch/data
networks:
  elastic_network:
    driver: bridge

volumes:
  esdata:
    driver: local

