version: '3'
services:
  elasticsearch:
    image: harbor.int.taqniat.ae/library/elasticsearch:8.16.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic_network
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: harbor.int.taqniat.ae/library/kibana:8.16.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elastic_network

networks:
  elastic_network:
    driver: bridge

volumes:
  esdata:
    driver: local
